export const RESOURCE_CATEGORIES = [
  { category: "ALL", label: "全部" },
  { category: "tools", count: 279, label: "工具" },
  { category: "frontend", count: 193, label: "前端" },
  { category: "java", count: 151, label: "Java" },
  { category: "python", count: 125, label: "Python" },
  { category: "javascript", count: 101, label: "Javascript" },
  { category: "tutorial", count: 84, label: "教程" },
  { category: "projectCode", count: 65, label: "项目代码" },
  { category: "productDesign", count: 62, label: "产品设计" },
  { category: "ai", count: 61, label: "AI" },
  { category: "interviewExp", count: 59, label: "面试经验" },
  { category: "golang", count: 57, label: "Go 语言" },
  { category: "onlineBook", count: 44, label: "文档" },
  { category: "algorithm", count: 38, label: "算法" },
  { category: "qa", count: 30, label: "Q&A" },
  { category: "pushIn", count: 28 },
  { category: "cplusplus", count: 27 },
  { category: "devPlatform", count: 24 },
  { category: "bigData", count: 20 },
  { category: "backend", count: 20 },
  { category: "softwareDev", count: 19 },
  { category: "csharp", count: 18 },
  { category: "php", count: 17 },
  { category: "c", count: 17 },
  { category: "safe", count: 16 },
  { category: "createColumn", count: 15 },
  { category: "operation", count: 14 },
  { category: "techTeam", count: 13 },
  { category: "interviewAnswer", count: 10 },
  { category: "gift", count: 8 },
  { category: "door", count: 8 },
  { category: "goodCreator", count: 8 },
  { category: "selfUp", count: 7 },
  { category: "contest", count: 6 },
  { category: "iot", count: 6 },
  { category: "jobUp", count: 6 },
  { category: "android", count: 5 },
  { category: "test", count: 5 },
  { category: "image", count: 4 },
  { category: "music", count: 4 },
  { category: "miniprogram", count: 4 },
  { category: "techExpert", count: 4 },
  { category: "news", count: 3 },
  { category: "blockchain", count: 3 },
  { category: "ios", count: 2 },
  { category: "research", count: 2 },
  { category: "coderLife", count: 1 },
  { category: "network", count: 1 },
  { category: "system", count: 1 },
  { category: "cloud", count: 1 }
];
